server: 
  port: 8081
  servlet: 
    context-path: /jwt-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-uat.corelogic.asia
          jwk-set-uri: https://auth-uat.corelogic.asia/ext/oauth/jwks